services:
  db:
    container_name: postgres_homework
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ny_taxi'
    ports:
      - '5433:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_homework
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin  

volumes:
  pgadmin_data:
